title: "ない機能は自分で作る！Chrome拡張機能開発入門"
summary: "Chrome拡張機能の作り方、ChromeWebStoreへの公開方法、拡張機能の収益化について学びます。"
topics: [JavaScript,html, Chrome拡張機能]
published: false
price: 500 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2
